Chapter 8 exercise 3
Why does the following code...

    def execute(block)
      block.call
    end

    execute { puts "Hello from inside the execute method!" }
    
Give us the following error when we run it?

    block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
    from test.rb:5:in `<main>'

A: In the definition of the .execute method, the ampersand is missing from the
parameter 'block'. The line should read 

    def execute(&block)
    
This way, the method knows to expect a block of code as an argument.